//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAngular.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel
    {
        public int Id { get; set; }
        public int Driver { get; set; }
        public int Places { get; set; }
        public int Origin { get; set; }
        public int Destination { get; set; }
        public byte[] Escales { get; set; }
        public System.DateTime Departure { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual User User { get; set; }
    }
}
